name: deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: push to gh-pages
      env:
        CNAME: http://www.ixda-vlr.tech
        FOLDER_NAME: build
        REACT_APP_ACCOUNTS_URL: ${{ secrets.REACT_APP_ACCOUNTS_URL }}
        REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_REDIRECT_URL: ${{ secrets.REACT_APP_REDIRECT_URL }}
      run: |
        unset CI
        npm ci
        npm run build
        echo $CNAME > build/CNAME
        git config user.name ripunjaynarula
        git add -f $FOLDER_NAME
        git commit --amend --no-edit
        git push origin `git subtree split --prefix $FOLDER_NAME master`:gh-pages --force ||  git subtree push --prefix $FOLDER_NAME origin gh-pages